### ISSUE TITLE
sapo.pt configuration file

### ISSUE THREAD

**Issue by marcoagpinto** [thundernest/autoconfig#7]
@Sancus 

Hello!

Here is the "sapo.pt" configuration file.

Remove the ".txt" from the filename.

When will it be available in Thunderbird for me to test?

Thanks!

[sapo.pt.txt](https://github.com/thundernest/autoconfig/files/3283921/sapo.pt.txt)

**Comment by benbucksch** [comment]
Hello Marco,

please first test the file yourself locally. See the "harddisk" 
mechanism listed on 
https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration 
.

The configuration looks good.

I checked the page and they also serve other domains. I checked and 
imap.sapo.cv and imap.meo.pt and imap.sapo.pt are all the same host. In 
such cases, where the ISP advertises different configurations, but they 
are actually all the same, we merge them into a single config file. So, 
please add `` and all the other domains:

```
<emailProvider id="sapo.pt">
       <domain>sapo.pt</domain>
<domain>sapo.cv</domain>
<domain>sapo.ao</domain>
<domain>sapo.mz</domain>
<domain>sapo.tl</domain>
<domain>mao.pt</domain>
       <displayName>SAPO Mail</displayName>

       ...

```


The rest of the file stays the same. They will all use imap.sapo.pt. 
That's OK (even if t he documentation says something else), because it's 
actually the same host, so it would work. We do the same for Yahoo, 
Hotmail etc.

Ben

**Comment by marcoagpinto** [comment]
@benbucksch 

Hello!

I have tested the .xml on the other computer with Thunderbird 68 beta 1 x64 (I am a beta tester and know the FTP URL) and it worked fine.

However, I don't know if the other stuff:
<domain>sapo.cv</domain> <domain>sapo.ao</domain> <domain>sapo.mz</domain> <domain>sapo.tl</domain> <domain>meo.pt</domain>

works since I am unable to test it.

Thank you!

Kind regards,
[sapo.pt.txt](https://github.com/thundernest/autoconfig/files/3285775/sapo.pt.txt)

**Comment by benbucksch** [comment]
Yes, I know you can only test the account that you have. I'm pretty sure 
it would work, though, because the ISP instructions say so, and I've 
verified that imap.sapo.pt == imap.sapo.cv, they are the same server, 
same IP address.

Ben

**Comment by marcoagpinto** [comment]
@benbucksch 
Can you commit the file and close the ticket?

I don't know how to do pull requests.

Thank you!
